### ISSUE TITLE
dipy_fit_dki fails with "argument --b0_threshold: invalid float value"

### ISSUE THREAD

**Issue by soichih** [brain-life/app-dipy-workflows#15] opened 2018-11-11 18:43 UTC
I've casually tested FIT DKI App on Brainlife and saw following error message.

```
/usr/local/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
usage: dipy_fit_dki [-h] [--b0_threshold float]
                    [--save_metrics [str [str ...]]] [--out_dir str]
                    [--out_dt_tensor str] [--out_fa str] [--out_ga str]
                    [--out_rgb str] [--out_md str] [--out_ad str]
                    [--out_rd str] [--out_mode str] [--out_evec str]
                    [--out_eval str] [--out_dk_tensor str] [--out_mk str]
                    [--out_ak str] [--out_rk str] [--force]
                    [--out_strat string] [--mix_names] [--log_level string]
                    [--log_file string]
                    input_files bvalues bvectors mask_files
dipy_fit_dki: error: argument --b0_threshold: invalid float value: 'null'

```

Is it broken?

**Comment by skoudoro** [comment] 2018-11-11 18:56
wow, I am surprised, What was your  b0_threshold value? the default one?

I will look into it

**Comment by skoudoro** [comment] 2018-11-12 16:52
I see, when we run the app, I get this:

```
running dipy_fit_dki    --force                 --out_dir /N/u/skoudoro/brainlife/5be9ad3c80ce40002a61e53d/5be9aebb80ce40002a61e544                 --b0_threshold null                 --out_strat what                 ../5be9ad3c80ce40002a61e53e/5b7ec606417c2c00432bdecc/dwi.nii.gz ../5be9ad3c80ce40002a61e53e/5b7ec606417c2c00432bdecc/dwi.bvals ../5be9ad3c80ce40002a61e53e/5b7ec606417c2c00432bdecc/dwi.bvecs ../5be9ad3c80ce40002a61e53e/5b7ec67f417c2c00432bdecd/mask.nii.gz
```

the problem is here: ` --b0_threshold null`. When you look at the config files, it is correct, `"b0_threshold ": 0.5`.

Does brainlife manage well float value or did I do something wrong ?

**Comment by skoudoro** [comment] 2018-11-12 17:10
I did something wrong... my bad...  an empty space in the app parameter just broke it.

the app is running as you can see [here](https://brainlife.io/project/5b23e74316fe38002748e679/process/5be9ad3c80ce40002a61e53d)

**Comment by soichih** [comment] 2018-11-12 17:13
Ah, so the b0_threshold option wasn't set at all.. DId you just add the b0_threshold option to Fit DKI App on BL? I just resubmitted it again and this time I see b0_threshold option set this time (and I am seeing a different error - I will open another issue for that)

**Comment by skoudoro** [comment] 2018-11-12 17:17
yeah,  I do not know why it was not set up. If I remove it before or what happens. 

Sorry for that, closing this issue

**Closed as completed by skoudoro** 2018-11-12 17:17 UTC
